version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    image: php:7-fpm
    volumes:
      - .:/var/www
